<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.16</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.gioorgi.pque</groupId>
	<artifactId>pque</artifactId>
	<version>1.0.2-SNAPSHOT</version>
	<packaging>jar</packaging>	
	<name>pque</name>
	<description>PostgreSQL super light message queue</description>

	<url>https://github.com/daitangio/pque/</url>	
	<developers>
		<developer>
			<name>Giovanni Giorgi</name>
			<email>jj@gioorgi.com</email>
			<roles><role>Major Leader</role></roles>
		</developer>
	</developers>
	<scm>
		<url>https://github.com/daitangio/pque/</url>
		<connection>scm:git:https://github.com/daitangio/pque.git</connection>
		<developerConnection>scm:git:https://github.com/daitangio/pque.git</developerConnection>
		<tag>1.0.1</tag>
	</scm>
	<issueManagement>
		<system>GitHub</system>
		<url>https://github.com/daitangio/pque/issues</url>
		
	</issueManagement>
	<licenses>
		<license>
            <name>The MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
		</license>
	</licenses>
	<properties>
		<java.version>11</java.version>
		<spring-boot.run.jvmArguments>
		-verbose:gc -server -Xms70m
		</spring-boot.run.jvmArguments>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
        </dependency>
		<dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>2.2.222</version>  <!-- Pushed version to resolve known vulnerabilities-->
			<scope>test</scope>
		</dependency>


		<dependency>
			<groupId>org.hibernate.validator</groupId>
			<artifactId>hibernate-validator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>

		<!-- START - Test dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-launcher</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- END - Test dependencies -->
	</dependencies>

	<distributionManagement>
	<snapshotRepository>
		<id>ossrh</id>
		<url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
	</snapshotRepository>
	<repository>
		<id>ossrh</id>
		<url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
	</repository>
	</distributionManagement>

	<build>
		<plugins>		
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>


			<plugin>
				<!-- Fixing version & activating "release" profile for those who use release plugin -->
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>3.1.1</version>
				<configuration>
					<autoVersionSubmodules>true</autoVersionSubmodules>

					<!-- Forward compatibility: "release-profile" will be removed from super POM.
						It's better to define javadocs, sources, signing, etc. in an independent "release" profile. -->
					<useReleaseProfile>true</useReleaseProfile>
					<releaseProfiles>release</releaseProfiles>
				</configuration>
			</plugin>

			<!-- needed for publishing -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>2.2.1</version>
				<executions>
					<execution>
					<id>attach-sources</id>
					<goals>
						<goal>jar-no-fork</goal>
					</goals>
					</execution>
				</executions>
				</plugin>
				<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.9.1</version>
				<executions>
					<execution>
					<id>attach-javadocs</id>
					<goals>
						<goal>jar</goal>
					</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

<profiles>
   <profile>
       <id>release</id>
       <build>
           <plugins>
               <plugin>
                   <groupId>org.sonatype.central</groupId>
                   <artifactId>central-publishing-maven-plugin</artifactId>
                   <version>0.6.0</version>
                   <extensions>true</extensions>
                   <configuration>
                       <publishingServerId>ossrh</publishingServerId>
                       <autoPublish>true</autoPublish>
                   </configuration>
               </plugin>

               <plugin>
                   <groupId>org.apache.maven.plugins</groupId>
                   <artifactId>maven-source-plugin</artifactId>
                   <version>3.3.1</version>
                   <executions>
                       <execution>
                           <id>attach-sources</id>
                           <goals>
                               <goal>jar-no-fork</goal>
                           </goals>
                       </execution>
                   </executions>
               </plugin>

               <plugin>
                   <groupId>org.apache.maven.plugins</groupId>
                   <artifactId>maven-javadoc-plugin</artifactId>
                   <version>3.10.1</version>
                   <executions>
                       <execution>
                           <id>attach-javadocs</id>
                           <goals>
                               <goal>jar</goal>
                           </goals>
                       </execution>
                   </executions>
               </plugin>

               <plugin>
                   <groupId>org.apache.maven.plugins</groupId>
                   <artifactId>maven-gpg-plugin</artifactId>
                   <version>3.2.4</version>
                   <executions>
                       <execution>
                           <id>sign-artifacts</id>
                           <phase>verify</phase>
                           <goals>
                               <goal>sign</goal>
                           </goals>
                       </execution>
                   </executions>
               </plugin>
           </plugins>
       </build>
   </profile>
</profiles>

</project>
